spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: seu-id
            client-secret: sua-chave
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com